### ISSUE TITLE
Automatically create folder for local adapter if not exist

### ISSUE THREAD

**Issue by JHGitty** [1up-lab/OneupFlysystemBundle#116]
For the local adapter you need to set a directory - of course.

But it might be helpful to have a `create: false` / `create: true` feature on the local adapter in the configuration file. The same feature exists on Gaufrette.

Example Gaufrette:
```
knp_gaufrette:
    adapters:
        example:
            local:
                directory: %storage_dir%/example/example2/
                create: true
```
