### ISSUE TITLE
Error after Symfony update 

### ISSUE THREAD

**Issue by graille** [1up-lab/OneupFlysystemBundle#133]
Hi !

Today, I've updated symfony, and from this moment, a strange issue is appeared

I've this error : 
> InvalidConfigurationException in ArrayNode.php line 317:
>  Unrecognized option "local" under "oneup_flysystem.adapters.local_adapter" 

My config : 
```
oneup_flysystem:
    adapters:
        local_adapter:
            local:
                directory: /srv/data/

    filesystems:
        default:
            adapter: local_adapter
```

The update : 
>  - Updating symfony/symfony (v3.2.3 => v3.2.4) Downloading: 100%         
>  - Updating sensio/framework-extra-bundle (v3.0.21 => v3.0.22) Downloading: 100%         
>  - Updating symfony/phpunit-bridge (v3.2.3 => v3.2.4) Loading from cache
