### ISSUE TITLE
Error on version config in AWS adapter

### ISSUE THREAD

**Issue by davidromani** [1up-lab/OneupFlysystemBundle#148]
Hello.

I'm following [this](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/adapter_awss3.md#awss3v3) instructions but I'm always getting this profiler error response:

```
InvalidArgumentException in ClientResolver.php line 374:
Missing required client configuration options: 

version: (string)

A "version" configuration value is required. Specifying a version constraint
ensures that your code will not be affected by a breaking change made to the
service. For example, when using Amazon S3, you can lock your API version to
"2006-03-01".

Your build of the SDK has the following version(s) of "s3": * "2006-03-01"

You may provide "latest" to the "version" configuration value to utilize the
most recent available API version that your client's API provider can find.
Note: Using 'latest' in a production application is not recommended.

A list of available API versions can be found on each client's API documentation
page: http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html. If you are
unable to load a specific API version, then you may need to update your copy of
the SDK.
```

My config files are:
```yml
# services.yml
    app.aws_s3.client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: "2006-03-01"
                region:  "%amazon_s3_region%"
                credentials:
                    key:    "%amazon_s3_acces_key%"
                    secret: "%amazon_s3_secret_key%"

# config.yml
oneup_flysystem:
    adapters:
        my_adapter:
            local:
                directory: "%kernel.root_dir%../web/media/uploads"
        s3_adapter:
            awss3v3:
                client: app.aws_s3.client
                bucket: "%amazon_s3_bucket_name%"
                prefix: ~
    filesystems:
        my_filesystem:
            adapter: my_adapter
```
Anybody can help me? Thanks.
