### ISSUE TITLE
Can't use env() in bundle configuration

### ISSUE THREAD

**Issue by Bukashk0zzz** [1up-lab/OneupFlysystemBundle#156]
Hi,

I use new [Dotenv](https://symfony.com/doc/current/components/dotenv.html) symfony component. 
I can't define adapter name using env parameter.

Get error [LogicException]  The adapter 'env_UPLOADS_PUBLIC_FLYSYSTEM_ADAPTER_e4fc4c42495a301a782e1f2d4704048f' is not defined.

My config:
```yml
oneup_flysystem:
    adapters:
        s3_public:
            awss3v3:
                client: aws.s3.client
                bucket: '%aws.s3.cdn.bucket%'
                prefix: '%env(UPLOADS_PUBLIC_PATH)%'

    filesystems:
        uploads_public:
            adapter: '%env(UPLOADS_PUBLIC_FLYSYSTEM_ADAPTER)%'
            mount: uploads_public
            visibility: public
            disable_asserts: false
```

**Comment by Algatux** [comment]
@Bukashk0zzz did you try to use a parameter ?


```
parameters:
    flysystem_adapter: '%env(UPLOADS_PUBLIC_FLYSYSTEM_ADAPTER)%' <---

oneup_flysystem:
    adapters:
        s3_public:
            awss3v3:
                client: aws.s3.client
                bucket: '%aws.s3.cdn.bucket%'
                prefix: '%env(UPLOADS_PUBLIC_PATH)%'

     filesystems:
        uploads_public:
            adapter: '%flysystem_adapter%' <---
            mount: uploads_public
            visibility: public
            disable_asserts: false`
```
