### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by tsdevelopment** [1up-lab/OneupFlysystemBundle#163]
Is there any example for Symfony 4 flex? I always get an error that my service could not be found.

**Comment by krish-damani** [comment]
I am also facing the same issue, any support would be much appreciable.

**Comment by francoispluchino** [comment]
The services are not found because the bundle creates services without the indication that they must be public. In Symfony Flex, the default config sets all services as private.

The version 3.0 adds support for Symfony 4.0, but does not include this change, so this should be considered a bug.

It is therefore necessary to define the services created by this bundle in public.

**Comment by jvahldick** [comment]
@tsdevelopment @krish-damani 

I am not sure if you are talking about the adapters and so, or the bundle's installation.
If it is regarding the installation, you can just require the bundle and install it as any other bundle.

```bash
$ composer require oneup/flysystem-bundle
``` 

If it related to the bundle configuration, as @francoispluchino the services by default are set as private, but you can simply create an alias for the services you wanna make public.

```yaml
services:
    app.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: "latest"
                region: "%env(AWS_S3_REGION)%"
                credentials:
                    key: "%env(AWS_S3_KEY)%"
                    secret: "%env(AWS_S3_SECRET)%"

    ### ### ### The alias to use in the controller
    app.my_filesystem:
        alias: "oneup_flysystem.app_filesystem"
        public: true

oneup_flysystem:
    adapters:
        app.s3_client_adapter:
            awss3v3:
                client: app.s3_client
                bucket: "%env(AWS_S3_BUCKET)%"
                prefix: ~

    filesystems:
        app:
            adapter: app.s3_client_adapter

``` 

Then you will be able to call your service.
```php
$fileSystem = $this->get('app.my_filesystem');
```
