### ISSUE TITLE
Invalid bucket configuration example in Google Cloud Storage adapter documentation

### ISSUE THREAD

**Issue by vladimirdotk** [1up-lab/OneupFlysystemBundle#170]
If you use this example: 
```yml
acme.google_storage_bucket:
    class: Google\Cloud\Storage\Bucket
    factory: 'acme.google_storage_client:bucket'
    arguments:
        name: 'your-bucket-name'
```
than `name` string will be added to url, so it will look like this: `https://storage.googleapis.com/storage/v1/b/name,your-bucket-name/o/file.txt`

That's why bucket part of config should look like this:
```yml
acme.google_storage_bucket:
    class: Google\Cloud\Storage\Bucket
    factory: 'acme.google_storage_client:bucket'
    arguments:
        - 'your-bucket-name'
```
