### ISSUE TITLE
wasabi.com adapter ?

### ISSUE THREAD

**Issue by grekpg** [1up-lab/OneupFlysystemBundle#172]
I use wasabi.com - its 100% amazon s3 compatibile - is possiible to use amazon s3 adapter ? 
i need in this way one thing - change base adres from amazonaws.com to wasabisys.com. I dont see that this param is configurable in bundle. (I use VichUploaderBundle + Gaufrette Bundle )

i get info from wasabi - https://wasabi-support.zendesk.com/hc/en-us/articles/360000363572-How-do-I-use-the-AWS-SDK-for-PHP-with-Wasabi- 
$s3Client = S3Client::factory(array(
'endpoint' => 'http://s3.wasabisys.com',
'profile' => 'wasabi',
'region' => 'us-east-1',
'version' => 'latest',
));
//Sample to create a bucket
$s3Client->createBucket(array('Bucket' => '<bucket-name>'));
so how to setup endpoint in adapter ?

**Comment by bytehead** [comment]
You can try to change the endpoint in your client service configuration as stated [here](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/adapter_awss3.md): 

```yaml
services:
    acme.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                endpoint: 'http://s3.wasabisys.com'
                version: '2006-03-01' # or 'latest'
                region: "region-id" # 'eu-central-1' for example
                credentials:
                    key: "s3-key"
                    secret: "s3-secret"
```
