### ISSUE TITLE
Owncloud

### ISSUE THREAD

**Issue by nckenn** [1up-lab/OneupFlysystemBundle#173]
Is it possible to use this bundle to be able to upload and read files in OwnCloud Server?

**Comment by digilist** [comment]
Yes, it's possible. As OwnCloud supports WebDAV you can simply use the [WebDAV adapter](https://github.com/thephpleague/flysystem-webdav). Configuration looks like something like this:

```yaml
oneup_flysystem:
    adapters:
        owncloud:
            webdav:
                client: my_webdav_client
                prefix: '/remote.php/webdav'

services:
    my_webdav_client:
        class: Sabre\DAV\Client
        arguments:
            - {baseUri: '%owncloud_url%', userName: '%owncloud_user%', password: '%owncloud_password%'}
```
