### ISSUE TITLE
[DX] Proposal: Consolidate filesystems, adapters and cache

### ISSUE THREAD

**Issue by weaverryan** [1up-lab/OneupFlysystemBundle#18]
Currently, configuration looks like this:

```yml
oneup_flysystem:
    cache:
        my_cache:
            noop: ~

    adapters:
        my_adapter:
            local:
                directory: %kernel.root_dir%/cache

    filesystems:
        my_filesystem:
            adapter: my_adapter
            cache: my_cache
```

I think splitting `adapters` and `cache` into its own sections might make sense for some edge-case re-usability, but it makes the bundle  harder to understand for new people. Also, by leveraging parameters, we still have a lot of re-usability with my proposal.

Here's what I propose:

```yml
oneup_flysystem:
    filesystems:
        my_filesystem:
            adapter:
                local:
                    directory: %kernel.root_dir%/cache
            cache:
                noop: ~
```

Thoughts? Thanks!
