### ISSUE TITLE
Error of configutation with Symfony 4

### ISSUE THREAD

**Issue by ThibautAlgrin** [1up-lab/OneupFlysystemBundle#193]
Hello

I installed and configured this bundle with Symfony like this:

```yaml
oneup_flysystem:
    adapters:
        adapter_sessions:
            local:
                directory: "%kernel.logs_dir%/../sessions"

    filesystems:
        sessions:
            adapter: adapter_sessions
            alias: League\Flysystem\Filesystem
            visibility: private
```

But I have this error, when I empty the Symfony cache:

```bash
Constructing service "oneup_flysystem.sessions_filesystem" from a parent definition is not supported at build time.
```

Any ideas ?
