### ISSUE TITLE
Custom adapter (lack of documentation) on Symfony 3.4

### ISSUE THREAD

**Issue by suiXz** [1up-lab/OneupFlysystemBundle#194]
Hello guys,

I'm using your bundle with the default adapter since a long time. Now i want to use a custom adapter but with only this documentation : https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/adapter_custom.md, i can't do it.

I'm using this adapter https://github.com/vyuldashev/flysystem-curlftp with little modification 
(add new configurable for ftps with certificate)

So i had a class like that : 

```php
namespace Ve\DelcoBundle\Service\Tools\FtpCurl;

class CurlFtpAdapter extends AbstractFtpAdapter
```

and a service declaration like that (service.yml):  

```yml
    ve_delco.service_tools_ftp_curl.curl_ftp_adapter:
        #abstract: true
        public: false
        class: Ve\DelcoBundle\Service\Tools\FtpCurl\CurlFtpAdapter
```

In config.yml : 

```yml
oneup_flysystem:
    adapters:
...
        grdf_ftps:
            custom:
                service: ve_delco.service_tools_ftp_curl.curl_ftp_adapter
...
    filesystems:
        omega_ftps:
            adapter: grdf_ftps
            visibility: public
            alias: 've_filesystem_omega_ftps'
            mount: omega_ftps
            plugins:
                - oneup_flysystem.plugin.list_files
                - ve_delco.service_tools_flysystem_plugins.list_files_by_regex_plugin
...
```

i tried to add configuration too but dont know how to do it 

Thank you in advance for your help !

PS : Sorry for my poor english
