### ISSUE TITLE
How to get directory

### ISSUE THREAD

**Issue by ahmed-bhs** [1up-lab/OneupFlysystemBundle#196]
I have this config and I want to get via `League\Flysystem\MountManager` service or another service the directory value inside a php controller !! Any idea would be appreciated
```
oneup_flysystem:
    adapters:
        nfs_adapter:
            local:
                directory: "/%dfs_nfs_path%/$var_dir$/$storage_dir$"
```
