### ISSUE TITLE
Google Storage Bucket - Symfony 5

### ISSUE THREAD

**Issue by aa-aahmed** [1up-lab/OneupFlysystemBundle#226]
### Bug Report
Following documentation to integrate with Google Storage Bucket, everything is ok but i am unable to register filesystem Please see below.

acme.google_storage_client:
        class: Google\Cloud\Storage\StorageClient
        arguments:
            - projectId: "xxxxxxxx"
              keyFilePath: '../xxxxxx.json' # optional

    acme.google_storage_bucket:
        class: Google\Cloud\Storage\Bucket
        factory: 'acme.google_storage_client:bucket'
        arguments:
            - 'your-bucket-name'

![image](https://user-images.githubusercontent.com/46661426/104684200-95f62680-574c-11eb-98e9-7daefda6742e.png)

Error: 
Invalid service "acme.google_storage_bucket": function "acme.google_storage_client:bucket" does not exist.

**Comment by bytehead** [comment]
This seems to be a documentation issue. Let me check.

**Comment by aa-aahmed** [comment]
thanks, 👍

**Comment by bytehead** [comment]
try this:
```yml
services:
    acme.google_storage_client:
        class: Google\Cloud\Storage\StorageClient
        arguments:
            - projectId: "your-project-id"
              keyFilePath: '/path/to/service-account.json' # optional

    acme.google_storage_bucket:
        class: Google\Cloud\Storage\Bucket
        factory: ['@acme.google_storage_client', 'bucket']
        arguments:
            - 'your-bucket-name'
```

Does this work in your case?
