### ISSUE TITLE
 Invalid service "cache.memcached": method "League\Flysystem\Cached\Storage\Memcached::addServer()" does not exist.

### ISSUE THREAD

**Issue by aa-aahmed** [1up-lab/OneupFlysystemBundle#227]
As per documentation after installing 
composer require league/flysystem-cached-adapter

Register the service 

```
services:
    cache.memcached:
        class: Memcached
        calls:
            - [ addServer, [ "memcached.domain.com", 11211 ]]

```
but after creating the service I get error on load.

**`**Invalid service "cache.memcached": method "League\Flysystem\Cached\Storage\Memcached::addServer()" does not exist.**`**

That's now I register service

```
services:
    cache.memcached:
        class: League\Flysystem\Cached\Storage\Memcached
        calls:
            - [ addServer, [ "127.0.0.1", 11211 ]]
```

**Comment by bytehead** [comment]
```
services:
    cache.memcached:
        class: League\Flysystem\Cached\Storage\Memcached
        calls:
            - [ addServer, [ "127.0.0.1", 11211 ]]
```

Thats wrong, you should use class `Memcached`, see https://www.php.net/manual/de/book.memcached.php.
