### ISSUE TITLE
google storage support?

### ISSUE THREAD

**Issue by adamgyongyosi** [1up-lab/OneupFlysystemBundle#237]
hy can you add google storage support?

**Comment by bytehead** [comment]
It's not available yet for flysystem v2. You can use version [3.x](https://github.com/1up-lab/OneupFlysystemBundle/tree/release/3.x) of this bundle instead.

**Comment by bytehead** [comment]
I've just spotted the adapter in the GitHub repo of flysystem (just missing in the docs). I'll add it 👍

**Comment by bytehead** [comment]
Closing in favor of #238.

**Comment by bytehead** [comment]
Can you test the branch `feature/google-cloud-storage`? :)

**Comment by adamgyongyosi** [comment]
working on another project, I need more time

**Comment by adamgyongyosi** [comment]
`
oneup_flysystem:
    adapters:
        public_uploads_adapter3:
            googlecloudstorage:
                bucket: "xxxx.appspot.com"
    filesystems:
        public_uploads_filesystem3:
            adapter: public_uploads_adapter3
`

**Comment by adamgyongyosi** [comment]
config/packages/oneup_flysystem.yaml
```yml
oneup_flysystem:
    adapters:
        public_uploads_adapter4:
            custom:
                service: flysystem.adapter.default.storage
    filesystems:
        public_uploads_filesystem4:
            adapter: public_uploads_adapter4
```

config/packages/dev/flysystem.yaml

```yml
flysystem:
    storages:
        default.storage:
            adapter: 'gcloud'
            options:
                client: 'gcloud_client_service' # The service ID of the Google\Cloud\Storage\StorageClient instance
                bucket: '%env(GOOGLE_CLOUD_STORAGE_BUCKET)%'

```
config/services.yaml

```yml
...
    gcloud_client_service:
        class: Google\Cloud\Storage\StorageClient
        arguments:
            - keyFilePath: '%env(GOOGLE_APPLICATION_CREDENTIALS)%'
...
```

config/packages/liip_imagine.yaml

```yml
liip_imagine:
    #    # valid drivers options include "gd" or "gmagick" or "imagick"
    #    driver: "gd"
    #
    webp:
        generate: true
    controller:
        redirect_response_code: 302
    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem4_filesystem
    # default loader to use for all filter sets
    data_loader: flysystem_loader
    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem4_filesystem
                cache_prefix: media/cache
                root_url: 'https://tratertesztcdn.silinfo.hu/'
                visibility: public
    # default cache resolver for saving thumbnails
    cache: flysystem_resolver
    filter_sets:
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size:          [500, 500]
                    mode:          outbound
                    allow_upscale: true

```
![image](https://user-images.githubusercontent.com/5511526/112613750-ba434300-8e20-11eb-9010-c3294f6e5c9c.png)
![image](https://user-images.githubusercontent.com/5511526/112613879-e8c11e00-8e20-11eb-804a-c5ea51aca9fd.png)
