### ISSUE TITLE
FTP Adapter configuration outdated

### ISSUE THREAD

**Issue by Tilotiti** [1up-lab/OneupFlysystemBundle#240]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 4.0.6

#### Summary

Hi !

I try to install a FTP adapter. Since the 4.x update, it seems that the configuration needed for this adapter changed, but the documentation is not up-to-date.

The documentation link : https://github.com/1up-lab/OneupFlysystemBundle/blob/master/doc/adapter_ftp.md

The change of configuration : https://github.com/1up-lab/OneupFlysystemBundle/pull/217/commits/aa595066126739897fdd4d7d3af9b4a20e65a8cc

#### How to reproduce

Install the 4.0.6 version (but it seems to be reproductible since 4.0), add an FTP adapter : 

```yaml
oneup_flysystem:
    adapters:
        ftp_adapter:
            ftp:
                host: '***'
                username: '***'
                password: '***'
    filesystems:
        ftp:
            adapter: ftp
```

I'll have now this error : 

     Unrecognized options "host, username, password" under "oneup_flysystem.adapters.carvivo_adapter.ftp". Available options are "connectionOptions", "connectionProvider", "connectivityChecker", "mimeTypeDetector", "visibilityConverter".
     
 This error is consistant with the configuration file, the problem is that the adapter configuration change and there is no documentation to show how to connect the new FTP adapter.

Thank you for your help :)
