### ISSUE TITLE
UTF-8 on FTP adapter

### ISSUE THREAD

**Issue by chrisooo3** [1up-lab/OneupFlysystemBundle#245]
### Bug Report

Problem with encoding utf-8 on FTP adtaper

#### How to reproduce
1) Set your config to this file:
```yaml
oneup_flysystem:
    adapters:
        ftp_adapter:
            ftp:
                host: ''
                username: ''
                password: ''
                port: 21
                root: '/'
                passive: true
                ssl: true
                timeout: 30
                utf8: true
```
2) Go to browser and see error:
```
Unrecognized option "utf8" under "oneup_flysystem.adapters.ftp_adapter.ftp". Available options are "host", "ignorePassiveAddress", "passive", "password", "permPrivate", "permPublic", "port", "recurseManually", "root", "ssl", "systemType", "timeout", "transferMode", "username".
```

**Comment by bytehead** [comment]
There is the `options` key missing (see docs: https://github.com/1up-lab/OneupFlysystemBundle/blob/main/doc/adapter_ftp.md)

```yaml
oneup_flysystem:
    adapters:
        ftp_adapter:
            ftp:
                options:
                    host: ''
                    username: ''
                    password: ''
                    port: 21
                    root: '/'
                    passive: true
                    ssl: true
                    timeout: 30
                    utf8: true
```

**Comment by bytehead** [comment]
Or are you using v3.x?

**Comment by chrisooo3** [comment]
@bytehead I am using `"oneup/flysystem-bundle": "^3.0"`

**Comment by bytehead** [comment]
Yep, PR is [here](246) :)

**Comment by chrisooo3** [comment]
@bytehead Thanks ;) when will you merge it? When it will be available on `packagist` to download it to my project?

**Comment by bytehead** [comment]
There you go: https://packagist.org/packages/oneup/flysystem-bundle#3.7.1

Thanks for reporting!

**Comment by chrisovato** [comment]
@bytehead No problem, do you have any idea how can I solve this [issue](https://stackoverflow.com/questions/68618625/how-to-upload-string-to-ftp-with-flysystem-and-utf-8)?

**Comment by chrisooo3** [comment]
@bytehead No problem, do u have an idea how can I solve this [issue](https://stackoverflow.com/questions/68618625/how-to-upload-string-to-ftp-with-flysystem-and-utf-8)?

**Comment by chrisooo3** [comment]
@bytehead After your PR, ftp file upload does not work. The files are empty on the server. When I downgrade to version `3.7.0` everything works fine. May you look at it?

**Comment by bytehead** [comment]
Weird. Can you describe your setup a bit more? How do you use the upload?

**Comment by chrisooo3** [comment]
The code that is responsible for uploading file to FTP server:
```php
...
use League\Flysystem\FilesystemInterface;

final class UploadToFTPHandler implements CommandHandlerInterface
{
    private FilesystemInterface $filesystem;

    public function __construct(FilesystemInterface $ftpFilesystem)
    {
        $this->filesystem = $ftpFilesystem;
    }

    public function __invoke(UploadToFTP $command): void
    {
        $fileContents = 'którzy uczestniczyć w procesie o stary zamek, niegdyś własność';
        $fileContents = mb_convert_encoding($fileContents, 'UTF-8');

        $this->filesystem->write(
            sprintf('%s.txt', uniqid()),
            $fileContents,
            ['mimetype' => 'text/plain; charset=utf-8']
        );
    }
}

```

Config file:
```yaml
oneup_flysystem:
    adapters:
        ftp_adapter:
            ftp:
                host: 'test.com'
                username: 'test.com'
                password: 'passwd'
                port: 21
                root: '/'
                passive: true
                ssl: true
                timeout: 30
```
