### ISSUE TITLE
Symfony configuration issue

### ISSUE THREAD

**Issue by pfuhrmann** [1up-lab/OneupFlysystemBundle#25]
Great bundle as first. I had to create factory wrapper class in order to go around symfony config file issue. Basically S3Client::factory requires config array as follows:

```php
array(
    'key' => 'aws-key', 
    'secret' => 'aws-secret'
)
```
How do you configure this as a service in the container?

From bundle docs I can see this setup:
```yaml
acme.s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            - ["s3-key", "s3-secret"]
```

But this does not work as this will create array as following:

```php
array(
    '0' => 'aws-key', 
    '1' => 'aws-secret'
)
```

Is this error in docs, recent change in aws-php library or am I just missing something?
