### ISSUE TITLE
Argument 2 passed to League\Flysystem\AwsS3V3\AwsS3V3Adapter::__construct() must be of the type string, null given, called in /home/habibun/Projects/test/vich-uploader-bundle/var/cache/dev/ContainerPOzBFIh/getOneupFlysystem_AwsFilesystemFilesystemService.php on line 27

### ISSUE THREAD

**Issue by habibun** [1up-lab/OneupFlysystemBundle#265]
### Bug Report                            
trying to implement AwsS3v3

Symfony  Version:  4.4.39 
PHP  Version:  7.4.28 
 "league/flysystem-aws-s3-v3": "^2.4",
"oneup/flysystem-bundle": "^4.4",

#### Summary

Argument 2 passed to League\Flysystem\AwsS3V3\AwsS3V3Adapter::__construct() must be of the type string, null given, called in /home/habibun/Projects/test/vich-uploader-bundle/var/cache/dev/ContainerPOzBFIh/getOneupFlysystem_AwsFilesystemFilesystemService.php on line 27

#### How to reproduce

git clone git@github.com:habibun/vich-uploader-bundle.git
composer install 
run local server
browse: /product/new [input value and submit]

**Comment by habibun** [comment]
Issue solved:

```
        aws_adapter:
            awss3v3:
                client: aws.s3_client
                bucket: ~
                prefix: ~
```
                
    Configuration `bucket` and `prefix` was empty, that's why
