### ISSUE TITLE
When following adapter_awss3.md and keep the default settings it errors.

### ISSUE THREAD

**Issue by johanadivare** [1up-lab/OneupFlysystemBundle#278]
### Bug Report

When i have the following config:
```yaml
oneup_flysystem:
    adapters:
        acme.flysystem_adapter:
            awss3v3:
                client: acme.s3_client
                bucket: ~
                prefix: ~
```
I get the following error: `League\Flysystem\AwsS3V3\AwsS3V3Adapter::__construct(): Argument #3 ($prefix) must be of type string, null given, called `

When i leave out `prefix` it works or setting `prefix: ''` also works. Is the handling of the setting wrong or should we change the docs?
