### ISSUE TITLE
Flysystem credentials problem with S3 adapter

### ISSUE THREAD

**Issue by sblmasta** [1up-lab/OneupFlysystemBundle#29]
I have problem in working Flysystem with Amazon S3 adapter.
I configured probably correct service and bundle but I can see credentials problem.
Here is the full error message:

> Error retrieving credentials from the instance profile metadata server. When you are not running inside of Amazon EC2, you must provide your AWS access key ID and secret access key in the "key" and "secret" options when creating a client or provide an instantiated Aws\Common\Credentials\CredentialsInterface object. ([curl] 52: Empty reply from server [url] http://169.254.169.254/latest/meta-data/iam/security-credentials/)

I'm using latest version of aws-sdk-php

```
"aws/aws-sdk-php": "2.7.*@dev"
```
### My service configuration

XXX is my key, ZZZ is secret.

``` yaml
services:
    flysystem.s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            - ["XXX", "ZZZ"]
```
### My adapter & filesystem configuration

``` yml
oneup_flysystem:
    adapters:
        my.flysystem_adapter:
            awss3:
                client: flysystem.s3_client
                bucket: myuniquebucketname
                prefix: ~
    filesystems:
        photos:
            adapter: my.flysystem_adapter
```
### PHP

When I try list elements in my bucket I received error with credentials.

``` php
$filesystem = $this->get('oneup_flysystem.photos_filesystem');
var_dump( $filesystem->listContents() );
```

I don't know what's wrong, so If anybody knows that, please help me :)
