### ISSUE TITLE
Cannot mount a fileSystem : No filesystem mounted with prefix 

### ISSUE THREAD

**Issue by jblanchon** [1up-lab/OneupFlysystemBundle#33]
here is my config (which is really simple),

```yml
oneup_flysystem:
    adapters:
        my_adapter:
            local:
                directory: %kernel.root_dir%/../../web/uploads
    filesystems:
        my_filesystem:
            adapter: my_adapter
```

and how I get my fileSytem :

```php
$this->mountManager->getFilesystem(“my_filesystem”);
```

But when i tried to get my fileSystem it give me this error : 
**No filesystem mounted with prefix my_filesystem**

Actually i'am using v0.4.1
thank you for your help

**Comment by tristanbes** [comment]
:up: Does anyone has an idea on what's happening ?

**Comment by sheeep** [comment]
Sorry. It seems I forgot to document this feature. Take a look at the [test configuration](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Tests/App/config/config.yml#L28).

```yml
oneup_flysystem:
    adapters:
        myadapter:
            local:
                directory: %kernel.root_dir%/cache

    filesystems:
        myfilesystem:
            adapter: myadapter
            mount:   prefix
```

```php
$mountManager->getFilesystem('prefix')
```

**Comment by tristanbes** [comment]
Thanks :-)

**Comment by jblanchon** [comment]
Hello,
Thank you for your help but it still not working.
I have updated my config 
```
oneup_flysystem:
    adapters:
        faq:
            local:
                directory: %kernel.root_dir%/../../web/uploads/faq
    filesystems:
        faq:
            adapter: faq
            mount:   prefix
```
and my code 
```
        $this->mountManager->getFilesystem('prefix');
        return $this->mountManager->getFilesystem('faq');
```
I've also updated the bundle in order to have the lastest version (dev-master)

**Comment by sheeep** [comment]
```php
// This will raise an error, because no filesystem with the mount-point *faq* is registered!
return $this->mountManager->getFilesystem('faq');
```

```php
// Should work
$this->mountManager->getFilesystem('prefix');
```

Can you tell me what you mean by "not working"? Take a look at [this function](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Tests/DependencyInjection/OneupFlysystemExtensionTest.php#L49-L55) in the tests.

```php
/** @var MountManager $mountManager */
$mountManager = $this->container->get('oneup_flysystem.mount_manager');
$this->assertInstanceOf('League\Flysystem\Filesystem', $mountManager->getFilesystem('prefix'));
```

Which [is configured](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Tests/App/config/config.yml#L24-L28) as this:

```yml
    filesystems:
        myfilesystem:
            adapter: myadapter
            cache:   mycache
            mount:   prefix
```

Can you debug the `MountManager` and tell me if there is something in [`MountManager::$filesystems`](https://github.com/thephpleague/flysystem/blob/master/src/MountManager.php#L54)
