### ISSUE TITLE
Rearrange the options array

### ISSUE THREAD

**Issue by yellow1912** [1up-lab/OneupFlysystemBundle#44]
Right now we are configuring the system like this:

```yaml
filesystems:
        s3_lib:
            adapter: s3_lib
            visibility: public
            cache: local
```

Then in the DI Extension we have to check manually:

```php
$options = [];
        if (array_key_exists('visibility', $config)) {
            $options['visibility'] = $config['visibility'];
        }
```

This will get troublesome later when new options are available etc. I suggest we change it to this:

```yaml
filesystems:
        s3_lib:
            adapter: s3_lib
            options:
                visibility: public
            cache: local
```

We can then easily use $config['options'] array in our DI Extension.
