### ISSUE TITLE
Global plugin attachment

### ISSUE THREAD

**Issue by sheeep** [1up-lab/OneupFlysystemBundle#45]
See https://github.com/1up-lab/OneupFlysystemBundle/pull/42

``` yml
oneup_flysystem:
    plugins:
        - global_plugin
    filesystems:
        my_filesystem:
            plugins:
                - local_plugin
```

> Whereas global_plugin is available for every configured filesystem and local_plugin only for my_filesystem.
