### ISSUE TITLE
You have requested a non-existent service "oneup_flysystem.my_filesystem"

### ISSUE THREAD

**Issue by toby-griffiths** [1up-lab/OneupFlysystemBundle#55]
I've tried setting up the file system as per the instructions, for use with AWS S3 buckets, however I'm being told that the service does not exist.

Using Xdebug I can trace that the compiler pass runs & seems to have the the service available during the cache clearing phase, but using container:debug, or attaempting to use the services in the wild report that it doesn't exists.

Here's my config…

````
# services.yml
services:
    # ...
    acme.s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                key: %s3_user%
                secret: %s3_secret%
````

````
# config.yml
oneup_flysystem:
    adapters:
        acme.flysystem_adapter:
            awss3v2:
                client: acme.s3_client
                bucket: %s3_bucket%
                prefix: ~
    filesystems:
        acme:
            adapter: acme.flysystem_adapter
            cache: ~
            alias: acme.flysystem
            mount: ~
````

Can anyone help me work out why the service is not available?

Thanks in advance

**Comment by carlcraig** [comment]
It would seem you are trying to get `oneup_flysystem.my_filesystem` which does not exist.

Check to see if you are trying to get `my` instead of `acme`.

The filesystem should be available via the alias `acme.flysystem` or `oneup_flysystem.acme_filesystem`.

**Comment by sheeep** [comment]
```
filesystems:
        acme:
            adapter: ~
            alias: acme.flysystem
```

This configuration will create a service called: `oneup_flysystem.acme_filesystem`, so the naming schema is the following:

`oneup_flysystem.%s_filesystem`, where `%s` is the key in your filesystems config. Additionally you choose to also alias the filesystem, so you can get it by providing the alias.

`$container->get('acme.flysystem');`

You can always get a list of registered services by calling the `container:debug` command. (`debug:container` for Symfony >=2.7)
