### ISSUE TITLE
Installation issue - 

### ISSUE THREAD

**Issue by ychoucha** [1up-lab/OneupFlysystemBundle#57]
Hello evrybody, well i relly like flystem, but i can't use it with my symfony program can help me please.

to install i do that  : 

so on frech symfony2 install : 
1> in composer.json i add this : 
```
{
    "require": {
        "oneup/flysystem-bundle": "@stable"
    }
}
```
after that i update my composer with command : 
``` php composer.phar update```

After that i add line on my config files : 
in appkernel.php 
```
   new Oneup\FlysystemBundle\OneupFlysystemBundle(),
```
and  in config.yml
```
oneup_flysystem:
    adapters:
        my_adapter:
            local:
                directory: %kernel.root_dir%/../uploads   
```

and now on y controler i want show a directory : 
```
<?php

namespace Demo\P1RetourDemo\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class DefaultController extends Controller
{
	/**
     * @Route("/")
     * @Template()
     */
    public function indexAction()
    {
    	$name = 'test Page de demmarage';
		
		$plugins = $container->findTaggedServiceIds('oneup_flysystem.plugin');
		
        return array('name' => $name);
    }
	
	
	
	/**
     * @Route("/FileRetourPs/{name}")
     * @Template()
     */
    public function fileRetourPsAction($name)
    {
        return array('name' => $name);
    }
}
```
and so when i lunch my page  i have this error : 
```
Whoops, looks like something went wrong.
1/1 ContextErrorException: Notice: Undefined variable: container in /var/www/demo01/Symfony/src/Demo/P1RetourDemoBundle/Controller/DefaultController.php line 20
```

so what is wrong please :

**Comment by ychoucha** [comment]
ok now i use this on my controller : 

<?php
namespace Pavillon\P1RetourPsBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local as Adapter;

class DefaultController extends Controller {	
    /**
     * @Route("/")
     * @Template()
     */
    public function indexAction()
    {
    	$name = 'test Page de demmarage';
		
		//$plugins = $container->findTaggedServiceIds('oneup_flysystem.plugin');
		
		$txt ="Hello world !";
		
		$filesystem = new Filesystem(new Adapter('/media/flyTest'));
		$filesystem->write('file.txt', $txt);
		
		
        return array('name' => $name);
    }
...


and i give permission on my directory like : 
sudo chmod 777 -R flyTest/

and after that's wokr.
can u please tell me if u se the good way ?

**Comment by sheeep** [comment]
The whole story of this bundle is to ease the usage of the Flysystem library. Refer to the [usage section in the documentation](https://github.com/1up-lab/OneupFlysystemBundle/blob/master/Resources/doc/filesystem_create.md#create-and-use-your-filesystems).

It seems like you didn't configure a filesystem. (Only an adapter)
Copied from the docs:

```
oneup_flysystem:
    adapters:
        my_adapter:
            local:
                directory: %kernel.root_dir%/cache

    filesystems:
        acme:
            adapter: my_adapter
```

`$filesystem = $container->get('oneup_flysystem.acme_filesystem');`

Oh, and this error:

> Whoops, looks like something went wrong.
1/1 ContextErrorException: Notice: Undefined variable: container in /var/www/demo01/Symfony/src/Demo/P1RetourDemoBundle/Controller/DefaultController.php line 20

There is of course no variable `$container` defined, like it is said in the error message. Try `$this->container` if you want to access the container in a Symfony controller.

**Comment by ychoucha** [comment]
sorry but it's not clear,

can u have a real user exemple please
to see how that's work.

**Comment by sheeep** [comment]
This *is* a real world example. Put the first block in your `app/config/config.yml` file, and you're free to use the flysystem in your controller like already mentioned above. (Second block)

```yml
# app/config/config.yml
oneup_flysystem:
    adapters:
        local_adapter:
            local:
                directory: %kernel.root_dir%/cache

    filesystems:
        local:
            adapter: local_adapter
```

```php
$filesystem = $container->get('oneup_flysystem.local_filesystem');
```

(I highlighted the important mapping parts)

The usage of Symfony-Services and or PHP-Variables is out of scope of this bundle, I'm afraid. But they are also well documented. :)

This is a bug tracker and should be used for reporting bugs or feature requests. Question can be asked on [StackOverflow](http://stackoverflow.com).
