### ISSUE TITLE
Error retrieving credentials from the instance profile metadata server

### ISSUE THREAD

**Issue by poulping** [1up-lab/OneupFlysystemBundle#92]
Hi,
I get a similar issue as the one described here in #29 
I do have the correct service definition though:

```
birdfeed.s3.client:
    class: Aws\S3\S3Client
    factory_class: Aws\S3\S3Client
    factory_method: factory
    arguments:
      -
        version: '2006-03-01'
        region: 'us-east-1'
        key: "myKey"
        secret: "mySecret"
```

Is there something I am doing wrong ?
